version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db:
    image: mongo:latest
    container_name: mongodb_container
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - mongodb_data:/data/db

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.33.2
    container_name: weaviate_container
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'generative-google'
      USE_GOOGLE_AUTH: 'true'
      CLUSTER_HOSTNAME: 'node1'
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_APIKEY: ${GOOGLE_APIKEY}

volumes:
  mongodb_data:
  weaviate_data:
  postgres_data:
