version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME
      - MONGODB_INITDB_ROOT_PASSWORD
      - MONGODB_INITDB_DATABASE
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
