"""Unlink tender_analysis from tenders table

Revision ID: 59c0efa6a1ba
Revises: dedbec864d0f
Create Date: 2025-11-06 19:01:19.709761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '59c0efa6a1ba'
down_revision: Union[str, Sequence[str], None] = 'dedbec864d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tender_analysis_tender_id_fkey'), 'tender_analysis', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('tender_analysis_tender_id_fkey'), 'tender_analysis', 'tenders', ['tender_id'], ['id'])
    # ### end Alembic commands ###
