"""new columns added

Revision ID: 7fc78eea6e7b
Revises: af37d21a19cf
Create Date: 2025-10-30 12:40:17.932484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7fc78eea6e7b'
down_revision: Union[str, Sequence[str], None] = 'af37d21a19cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('drive_folders', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'drive_folders')
    # ### end Alembic commands ###
